[build]
  command = "echo 'Build complete'"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/chat"
  status = 200

[functions]
  directory = "netlify/functions"
